# Generated by Django 2.2 on 2019-04-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('image_url', models.CharField(default='', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(default='', max_length=600)),
                ('subject', models.CharField(default='', max_length=200)),
                ('school', models.ForeignKey(on_delete='CASCADE', related_name='professors', to='todo.School')),
            ],
        ),
    ]
