# Generated by Django 2.2 on 2019-04-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_professor_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='education',
        ),
    ]
