# Generated by Django 2.2 on 2019-04-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_professor_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='education',
            field=models.CharField(default='', max_length=200),
        ),
    ]
